// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsda18L2Rv4tlCkEg3Uhkg-d92ARgo9UU',
    appId: '1:716458013769:web:0be0b9aac65082c790fb98',
    messagingSenderId: '716458013769',
    projectId: 'digital-student-path-77a7e',
    authDomain: 'digital-student-path-77a7e.firebaseapp.com',
    storageBucket: 'digital-student-path-77a7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXU68gjani8X9ir1a1g-dsSn-FkuUzdRE',
    appId: '1:716458013769:android:69a2091ee215120b90fb98',
    messagingSenderId: '716458013769',
    projectId: 'digital-student-path-77a7e',
    storageBucket: 'digital-student-path-77a7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YSiopSB1GWvuAC1FurXa5SV5L_vzveI',
    appId: '1:716458013769:ios:79d6f75a651d589190fb98',
    messagingSenderId: '716458013769',
    projectId: 'digital-student-path-77a7e',
    storageBucket: 'digital-student-path-77a7e.firebasestorage.app',
    iosBundleId: 'com.example.digitalStudentPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-YSiopSB1GWvuAC1FurXa5SV5L_vzveI',
    appId: '1:716458013769:ios:79d6f75a651d589190fb98',
    messagingSenderId: '716458013769',
    projectId: 'digital-student-path-77a7e',
    storageBucket: 'digital-student-path-77a7e.firebasestorage.app',
    iosBundleId: 'com.example.digitalStudentPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsda18L2Rv4tlCkEg3Uhkg-d92ARgo9UU',
    appId: '1:716458013769:web:47c5c0bd06da677290fb98',
    messagingSenderId: '716458013769',
    projectId: 'digital-student-path-77a7e',
    authDomain: 'digital-student-path-77a7e.firebaseapp.com',
    storageBucket: 'digital-student-path-77a7e.firebasestorage.app',
  );
}
